language: generic
dist: bionic
os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'

matrix:
  include:
    - os: osx
      env:
        #        - CXX=clang++ PATH=/usr/local/opt/llvm@10/bin:$PATH LLVM_DIR=/usr/local/opt/llvm@10 LDFLAGS:=-L/usr/local/opt/llvm@10/lib CPPFLAGS=-I/usr/local/opt/llvm@10/include
        - CONFIG_ARGS="-DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++"
      install: brew install llvm@10
      cache:
        directories: ~/Library/Caches/Homebrew/
env:
  global:
    - PATH=$TRAVIS_BUILD_DIR/cmake-3.8.1-Linux-x86_64/bin:$PATH
  matrix:
    - CONFIG_ARGS="-DCMAKE_BUILD_TYPE:STRING=Debug"
    - CONFIG_ARGS=
install: curl https://cmake.org/files/v3.8/cmake-3.8.1-Linux-x86_64.tar.gz | tar xz
script: . ./build.sh && ./build.sh debug